// actionTypes.js

// register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


// create blog
export const CREATEBLOG_REQUEST = 'CREATEBLOG_REQUEST';
export const CREATEBLOG_SUCCESS = 'CREATEBLOG_SUCCESS';
export const CREATEBLOG_FAILURE = 'CREATEBLOG_FAILURE';

// update blog

export const UPDATEBLOG_REQUEST = 'UPDATEBLOG_REQUEST';
export const UPDATEBLOG_SUCCESS = 'UPDATEBLOG_SUCCESS';
export const UPDATEBLOG_FAILURE = 'UPDATEBLOG_FAILURE';

// delete blog

export const DELETEBLOG_REQUEST = 'DELETEBLOG_REQUEST';
export const DELETEBLOG_SUCCESS = 'DELETEBLOG_SUCCESS';
export const DELETEBLOG_FAILURE = 'DELETEBLOG_FAILURE';

// display all blog

export const DISPLAYALLBLOG_REQUEST = 'DISPLAYALLBLOG_REQUEST';
export const DISPLAYALLBLOG_SUCCESS = 'DISPLAYALLBLOG_SUCCESS';
export const DISPLAYALLBLOG_FAILURE = 'DISPLAYALLBLOG_FAILURE';

// display all blogs by user

export const DISPLAY_ALL_BLOGS_BY_USER_REQUEST = 'DISPLAY_ALL_BLOGS_BY_USER_REQUEST';
export const DISPLAY_ALL_BLOGS_BY_USER_SUCCESS = 'DISPLAY_ALL_BLOGS_BY_USER_SUCCESS';
export const DISPLAY_ALL_BLOGS_BY_USER_FAILURE = 'DISPLAY_ALL_BLOGS_BY_USER_FAILURE';

// display homepage blogs

export const DISPLAY_HOMEPAGE_BLOGS_REQUEST = 'DISPLAY_HOMEPAGE_BLOGS_REQUEST';
export const DISPLAY_HOMEPAGE_BLOGS_SUCCESS = 'DISPLAY_HOMEPAGE_BLOGS_SUCCESS';
export const DISPLAY_HOMEPAGE_BLOGS_FAILURE = 'DISPLAY_HOMEPAGE_BLOGS_FAILURE';

// get all the users
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';



// follow and unfollow --> will be under user action

export const FOLLOW_REQUEST = 'FOLLOW_REQUEST';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAILURE = 'FOLLOW_FAILURE';

export const UNFOLLOW_REQUEST = 'UNFOLLOW_REQUEST';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
export const UNFOLLOW_FAILURE = 'UNFOLLOW_FAILURE';